Id: CompanyName.ProductName
Version: 20.05.456
Name: Test Product
Publisher: Test Publisher
Homepage: https://example.com/test
License: Copyright (C) Test Company
Description: The test product description.
Installers:
    - Arch: x86
      Url: https://github.com/mjcheetham/workflow-test/releases/download/v20.05.456/test-20.05.456.exe
      InstallerType: Inno
      Sha256: 6b3a55e0261b0304143f805a24924d0c1c44524821305f31d9277843b8a10f4e